version: "3.9"
services:
  # ---------- business services ----------
  favourite:
    build: ./MusicApp.Favourites.API
    container_name: favourite
    ports:
      - "5001:8080"
    networks: [ musicnet ]
  
  music:
    build: ./MusicApp.Music.API
    container_name: music
    ports:
      - "5002:8080"
    networks: [ musicnet ]
  
  identity:
    build: ./MusicApp.Identity.API
    container_name: identity
    ports:
      - "5003:8080"
    networks: [ musicnet ]

  gateway:
    build: ./MusicApp.Gateway
    container_name: gateway
    depends_on:
      - favourite
      - music
      - identity
    ports:
      - "8000:8000"
    networks: [ musicnet ]
  frontend:
    build: ./MusicApp.UI
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks: [ musicnet ]
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "MsSql123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
    networks: [ musicnet ]
networks:
  musicnet:
    driver: bridge
volumes:
  sql_data: